apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::374118089533:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-175YMOHATRIFM
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::374118089533:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-27T20:31:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2240"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: bf6939f4-91d8-4856-bf84-a134b0ac9ad2
