apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::021105578484:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::021105578484:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-9RWBFV37YH1D
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-27T01:04:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "97754"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 082a3971-5e49-4224-896d-f9476a1f8d3a
